Repository ONSdigital/eq-survey-runner, pull requests merged in 2019-05, with the labels that each got.

#2078 Fixed q_codes and NI change
  data/en/stocks_0070.json
Labels: v2

#2056 Fix error when feedback form submitted after questionnaire submitted.
  app/helpers/template_helper.py
  app/views/feedback.py
  tests/integration/views/test_feedback.py
Labels: v2

#2083 Change stocks validations to use metadata values.
  data/en/stocks_0001.json
  data/en/stocks_0002.json
  data/en/stocks_0003.json
  data/en/stocks_0004.json
  data/en/stocks_0005.json
  data/en/stocks_0006.json
  data/en/stocks_0007.json
  data/en/stocks_0008.json
  data/en/stocks_0009.json
  data/en/stocks_0010.json
  data/en/stocks_0011.json
  data/en/stocks_0012.json
  data/en/stocks_0013.json
  data/en/stocks_0014.json
  data/en/stocks_0033.json
  data/en/stocks_0034.json
  data/en/stocks_0051.json
  data/en/stocks_0052.json
  data/en/stocks_0057.json
  data/en/stocks_0058.json
  data/en/stocks_0061.json
  data/en/stocks_0070.json
Labels: v2

#2080 Stocks content fixes
  data/en/stocks_0001.json
  data/en/stocks_0002.json
  data/en/stocks_0003.json
  data/en/stocks_0004.json
  data/en/stocks_0005.json
  data/en/stocks_0006.json
  data/en/stocks_0007.json
  data/en/stocks_0008.json
  data/en/stocks_0009.json
  data/en/stocks_0010.json
  data/en/stocks_0011.json
  data/en/stocks_0012.json
  data/en/stocks_0013.json
  data/en/stocks_0014.json
  data/en/stocks_0033.json
  data/en/stocks_0034.json
  data/en/stocks_0051.json
  data/en/stocks_0052.json
  data/en/stocks_0057.json
  data/en/stocks_0058.json
  data/en/stocks_0061.json
  data/en/stocks_0070.json
Labels: v2

#2087 Add missing routing rules for stocks 0013 and 0014.
  data/en/stocks_0013.json
  data/en/stocks_0014.json
Labels: v2

#2081 Applied question page title style to calculated summary page title
  app/templates/summary.html
Labels: v2

#2030 Updated MBS 0111 adding guidance and removing preview section
  app/helpers/template_helper.py
  app/templates/introduction.html
  app/templates/partials/introduction/basic.html
  app/templates/partials/introduction/preview.html
  app/templates/partials/introduction/start-survey.html
Labels: Don't Merge, v2

#2071 Adding Google Tag Manager
  README.md
  app/helpers/template_helper.py
  app/settings.py
  app/setup.py
  app/templates/layouts/_base.html
  app/validation/validators.py
  app/views/errors.py
  app/views/questionnaire.py
  app/views/session.py
  app/views/static.py
  tests/integration/test_app_create.py
  tests/integration/test_application_variables.py
Labels: v2

#2094 Add description to stocks currency questions
  data/en/stocks_0001.json
  data/en/stocks_0002.json
  data/en/stocks_0003.json
  data/en/stocks_0004.json
  data/en/stocks_0005.json
  data/en/stocks_0006.json
  data/en/stocks_0007.json
  data/en/stocks_0008.json
  data/en/stocks_0009.json
  data/en/stocks_0010.json
  data/en/stocks_0011.json
  data/en/stocks_0012.json
  data/en/stocks_0013.json
  data/en/stocks_0014.json
  data/en/stocks_0033.json
  data/en/stocks_0034.json
  data/en/stocks_0051.json
  data/en/stocks_0052.json
  data/en/stocks_0057.json
  data/en/stocks_0058.json
  data/en/stocks_0061.json
  data/en/stocks_0070.json
Labels: v2

#2105 Change Wales census day from Sept -> June 12
  data/cy/census_individual_gb_wls.json
Labels: critical (P1)

#2103 Census Individual Proxy Content changes
  data/cy/census_individual_gb_wls.json
Labels: critical (P1)

#2107 Add latest static Welsh translations
  app/translations/cy/LC_MESSAGES/messages.mo
  app/translations/cy/LC_MESSAGES/messages.po
Labels: critical (P1)

#2106 Content changes for Stocks
  data/en/stocks_0001.json
  data/en/stocks_0002.json
  data/en/stocks_0003.json
  data/en/stocks_0004.json
  data/en/stocks_0005.json
  data/en/stocks_0006.json
  data/en/stocks_0007.json
  data/en/stocks_0008.json
  data/en/stocks_0009.json
  data/en/stocks_0010.json
  data/en/stocks_0011.json
  data/en/stocks_0012.json
  data/en/stocks_0013.json
  data/en/stocks_0014.json
  data/en/stocks_0033.json
  data/en/stocks_0034.json
  data/en/stocks_0051.json
  data/en/stocks_0052.json
  data/en/stocks_0057.json
  data/en/stocks_0058.json
  data/en/stocks_0061.json
  data/en/stocks_0070.json
Labels: v2
